# Generated by Django 5.1.3 on 2024-11-10 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_address_options_address_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='name',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
        migrations.AddField(
            model_name='address',
            name='phone',
            field=models.CharField(default='Not Provided', max_length=255),
        ),
    ]
